name: ci

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install dependencies
        run: python3 -m pip install pytest
      - name: test
        run: make test

  build-linux:
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: test
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pypa/build
      run: python -m pip install build --user

    - name: Build a source tarball
      run: python -m build --sdist --outdir dist/ .

    - name: Store the binary wheel
      uses: actions/upload-artifact@v2
      with:
        name: python-package-distributions
        path: dist

  publish:
    name: Publish to PyPI and TestPyPI
    runs-on: ubuntu-latest
    needs: build-linux

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v2
      with:
        name: python-package-distributions
        path: dist/

#    - name: Publish distribution 📦 to Test PyPI
#      uses: pypa/gh-action-pypi-publish@master
#      with:
#       password: ${{ secrets.TEST_PYPI_API_TOKEN }}
#       repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
